version: '3.9'
services:
  client:
    build: client
    ports:
      - '3000:3000'

  event-bus:
    build: event-bus

  events:
    build: events
    ports:
      - '3004:3004'

  gmail:
    build: gmail
    ports:
      - '3002:3002'

  people:
    build: people
    ports:
      - '3001:3001'

  yelp:
    build: yelp
    ports:
      - '3003:3003'

  events-db:
    image: mongo:latest
    volumes:
      - events-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: eventadmin
      MONGO_INITDB_ROOT_PASSWORD: event

  people-db:
    image: mongo:latest
    volumes:
      - people-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: people
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  events-data:
  people-data:
